spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      #monitorar ao menos 10 requisições antes de abrir o circuito
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      # porcentagem de requisições com erro necessárias para abrir o circuito
      failureRateThreshold: 50
      # tempo necessário para passar de aberto para semi-aberto. 10.000ms (10s)
      waitDurationInOpenState: 10000